require 'json'

array_en = [
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguans",
    "Argentinean",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Barbudans",
    "Batswana",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djibouti",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirian",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Herzegovinian",
    "Honduran",
    "Hungarian",
    "I-Kiribati",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourger",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivan",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Moroccan",
    "Mosotho",
    "Motswana",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Northern Irish",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovakian",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamer",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian or Tobagonian",
    "Tunisian",
    "Turkish",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbekistani",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemenite",
    "Zambian",
    "Zimbabwean"
]

array_fr = [
    "Afghan",
    "Albanais",
    "Algérien",
    "Américain",
    "Andorran",
    "Angolais",
    "Antiguans",
    "Argentin",
    "Arménien",
    "Australien",
    "Autrichien",
    "Azerbaïdjanais",
    "Bahamian",
    "Bahreïn",
    "Bangladais",
    "Barbadian",
    "Barbudans",
    "Batswana",
    "Biélorusse",
    "Belge",
    "Belizean",
    "Béninois",
    "Bhoutanais",
    "Bolivien",
    "Bosniaque",
    "Brésilien",
    "Britanique",
    "Bruneian",
    "Bulgare",
    "Burkinabé",
    "Birman",
    "Burundais",
    "Cambodgien",
    "Camerounais",
    "Canadien",
    "Cap-verdien",
    "Centrafricain",
    "Tchadien",
    "Chilien",
    "Chinois",
    "Colombien",
    "Comoran",
    "Congolais",
    "Costaricain",
    "Croate",
    "Cubain",
    "Chypriote",
    "Tchèque",
    "Danois",
    "Djibouti",
    "Dominicain",
    "Néerlandais",
    "Timorais de l'Est",
    "Équatorien",
    "Égyptien",
    "Emirian",
    "Équato-guinéen",
    "Érythréen",
    "Estonien",
    "Éthiopien",
    "Fidjien",
    "Philippin",
    "Finlandais",
    "Français",
    "Gabonais",
    "Gambien",
    "Géorgien",
    "Allemand",
    "Ghanéen",
    "Grec",
    "Grenadian",
    "Guatémaltèque",
    "Guinée-Bissauan",
    "Guinéen",
    "Guyanais",
    "Haïtien",
    "Herzégovine",
    "Hondurien",
    "Hongrois",
    "I-Kiribati",
    "Islandais",
    "Indien",
    "Indonésien",
    "Iranien",
    "Irakien",
    "Irlandais",
    "Israélien",
    "Italien",
    "Ivoirien",
    "Jamaïquain",
    "Japonais",
    "Jordanien",
    "Kazakhstani",
    "Kenyan",
    "Kittian and Nevisian",
    "Koweïtien",
    "Kirghize",
    "Laotien",
    "Letton",
    "Libanais",
    "Libérien",
    "Libyen",
    "Liechtenstein",
    "Lituanien",
    "Luxembourgeois",
    "Macédonien",
    "Malgache",
    "Malawian",
    "Malaisien",
    "Maldivan",
    "Malien",
    "Maltais",
    "Marshallese",
    "Mauritanien",
    "Mauricien",
    "Mexicain",
    "Micronésien",
    "Moldave",
    "Monacan",
    "Mongol",
    "Marocain",
    "Mosotho",
    "Motswana",
    "Mozambicain",
    "Namibien",
    "Nauruan",
    "Népalais",
    "Néo-Zélandais",
    "Nicaraguayen",
    "Nigérian",
    "Nigerien",
    "Nord coréen",
    "Northern Irish",
    "Norvégien",
    "Omani",
    "Pakistanais",
    "Palauan",
    "Panaméen",
    "Papouasie-Nouvelle-Guinée",
    "Paraguayen",
    "Péruvien",
    "Polonais",
    "Portugais",
    "Qatari",
    "Roumain",
    "Russe",
    "Rwandais",
    "Saint Lucian",
    "Salvadorien",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saoudien",
    "Écossais",
    "Sénégalais",
    "Serbe",
    "Seychellois",
    "Sierra Léonais",
    "Singapourien",
    "Slovaque",
    "Slovène",
    "Salomon Islander",
    "Somali",
    "Sud africain",
    "Sud coréen",
    "Espagnol",
    "Sri lankais",
    "Soudanais",
    "Surinamer",
    "Swazi",
    "Suédois",
    "Suisse",
    "Syrien",
    "Taïwanais",
    "Tadjik",
    "Tanzanien",
    "Thaïlandais",
    "Togolais",
    "Tongan",
    "Trinidadien ou Tobagonien",
    "Tunisien",
    "Turc",
    "Tuvaluan",
    "Ougandais",
    "Ukrainien",
    "Uruguayen",
    "Ouzbékistan",
    "Vénézuélien",
    "Vietnamien",
    "Gallois",
    "Yéménite",
    "Zambien",
    "Zimbabwéen"
]

fr_hash = Hash[(1...array_fr.size).zip array_fr]
File.open("nationalities_fr.json", "w") do |f|
    f.write(fr_hash.to_json)
end

en_hash = Hash[(1...array_en.size).zip array_en]
File.open("nationalities_en.json", "w") do |f|
    f.write(en_hash.to_json)
end